ALTER TYPE "ResearchMaterialItemStatus" ADD VALUE IF NOT EXISTS 'DOWNLOADING';
ALTER TYPE "ResearchMaterialItemStatus" ADD VALUE IF NOT EXISTS 'DOWNLOADED';
ALTER TYPE "ResearchMaterialItemStatus" ADD VALUE IF NOT EXISTS 'FAILED';
